//! Pre-render the winged-sneaker PNG as Unicode Braille (same 2×4 dots as caduceus).
//!
//! Each cell is tagged wing vs sneaker so the TUI can color them separately.
//! The source PNG is large; the TUI ships the braille + tone rows instead.

use std::{env, fs, path::Path};

use image::{imageops::FilterType, RgbaImage};

const PNG: &[u8] = include_bytes!("design/layer-winged-sneaker.png");
/// Terminal columns. Each cell is 2×4 pixels (Braille). Height follows aspect.
/// 24 cols → ~14 rows, so the full sneaker fits under the wordmark.
const COLS: u32 = 24;
const ALPHA_ON: u8 = 13;
/// Light pixels become dots (white shoe / wings on a dark field).
const INK: f64 = 128.0;

/// Braille dots in Unicode bit order:
/// ```text
/// 1 4
/// 2 5
/// 3 6
/// 7 8
/// ```
const DOTS: [(u32, u32, u32); 8] = [
    (0, 0, 0x01),
    (0, 1, 0x02),
    (0, 2, 0x04),
    (1, 0, 0x08),
    (1, 1, 0x10),
    (1, 2, 0x20),
    (0, 3, 0x40),
    (1, 3, 0x80),
];

fn main() {
    let img = image::load_from_memory(PNG).expect("decode mascot png");
    let rows = to_braille(&img.to_rgba8(), COLS);
    let out = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out).join("mascot_data.rs"), emit_rs(&rows))
        .expect("write mascot_data.rs");
    // Gallery story: same PNG via logo-art half-blocks (24-bit, not theme tokens).
    let ansi = logo_art::image_to_ansi(PNG, 28);
    fs::write(Path::new(&out).join("mascot-logo-art.ansi"), ansi).expect("write logo-art ansi");
    println!("cargo::rerun-if-changed=design/layer-winged-sneaker.png");
}

fn emit_rs(rows: &[(String, String)]) -> String {
    let mut s = String::from(
        "// @generated by build.rs from design/layer-winged-sneaker.png\n\
         // Each row: (braille glyphs, per-cell tones). `1` = wing, `2` = sneaker, `0` = empty.\n\
         pub const MASCOT_ROWS: &[(&str, &str)] = &[\n",
    );
    for (glyphs, tones) in rows {
        s.push_str("    (\"");
        s.push_str(glyphs);
        s.push_str("\", \"");
        s.push_str(tones);
        s.push_str("\"),\n");
    }
    s.push_str("];\n");
    s
}

fn to_braille(img: &RgbaImage, cols: u32) -> Vec<(String, String)> {
    let cropped = crop_opaque(img);
    let (w, h) = cropped.dimensions();
    let tw = cols * 2;
    let th = {
        let raw = ((h as f64 * tw as f64) / w as f64).round() as u32;
        raw.div_ceil(4) * 4
    };
    let small = image::imageops::resize(&cropped, tw, th, FilterType::Lanczos3);

    let mut rows = Vec::new();
    for y in (0..th).step_by(4) {
        let mut glyphs = String::new();
        let mut tones = String::new();
        for x in (0..tw).step_by(2) {
            let mut bits = 0u32;
            let mut wing = 0u32;
            let mut sneaker = 0u32;
            for (dx, dy, bit) in DOTS {
                let px = x + dx;
                let py = y + dy;
                if px >= tw || py >= th || !is_ink(&small, px, py) {
                    continue;
                }
                bits |= bit;
                if is_wing(px, py, tw, th) {
                    wing += 1;
                } else {
                    sneaker += 1;
                }
            }
            glyphs.push(char::from_u32(0x2800 + bits).expect("braille"));
            tones.push(if bits == 0 {
                '0'
            } else if wing >= sneaker {
                '1'
            } else {
                '2'
            });
        }
        rows.push((glyphs, tones));
    }
    while rows
        .first()
        .is_some_and(|(_, t)| t.chars().all(|c| c == '0'))
    {
        rows.remove(0);
    }
    while rows
        .last()
        .is_some_and(|(_, t)| t.chars().all(|c| c == '0'))
    {
        rows.pop();
    }
    rows
}

/// Left feathers + the inner-wing peak are gold. The shoe collar (the mass
/// under the inner wing, toward the laces) is mint — not a horizontal wash.
fn is_wing(x: u32, y: u32, w: u32, h: u32) -> bool {
    let nx = f64::from(x) / f64::from(w);
    let ny = f64::from(y) / f64::from(h);
    if nx < 0.42 {
        ny < 0.56
    } else if nx < 0.54 {
        ny < 0.38
    } else {
        false
    }
}

fn crop_opaque(img: &RgbaImage) -> RgbaImage {
    let (w, h) = img.dimensions();
    let mut minx = w;
    let mut miny = h;
    let mut maxx = 0u32;
    let mut maxy = 0u32;
    for y in 0..h {
        for x in 0..w {
            if img.get_pixel(x, y).0[3] >= ALPHA_ON {
                minx = minx.min(x);
                miny = miny.min(y);
                maxx = maxx.max(x);
                maxy = maxy.max(y);
            }
        }
    }
    if minx > maxx {
        return img.clone();
    }
    image::imageops::crop_imm(img, minx, miny, maxx - minx + 1, maxy - miny + 1).to_image()
}

fn is_ink(img: &RgbaImage, x: u32, y: u32) -> bool {
    let [r, g, b, a] = img.get_pixel(x, y).0;
    if a < ALPHA_ON {
        return false;
    }
    let lum = 0.299 * f64::from(r) + 0.587 * f64::from(g) + 0.114 * f64::from(b);
    lum >= INK
}
